apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-namespace-prod

images:
  - name: PROJECT/BC_IMAGE
    newName: deecaad/devopsk8s
    newTag: todo-backup-prod-b431f43d418b714b89bb1a9eb14739cefc100905
  - name: PROJECT/BD_IMAGE
    newName: deecaad/devopsk8s
    newTag: todo-broadcaster-prod-b431f43d418b714b89bb1a9eb14739cefc100905
  - name: PROJECT/B_IMAGE
    newName: deecaad/devopsk8s
    newTag: todo-backend-prod-b431f43d418b714b89bb1a9eb14739cefc100905
  - name: PROJECT/F_IMAGE
    newName: deecaad/devopsk8s
    newTag: todo-frontend-prod-b431f43d418b714b89bb1a9eb14739cefc100905
  - name: PROJECT/G_IMAGE
    newName: deecaad/devopsk8s
    newTag: todo-generator-prod-b431f43d418b714b89bb1a9eb14739cefc100905

resources:
  - ./../../base
  - ./manifests/configmap.yaml

patchesJson6902:
  - patch: |-
      - op: replace
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
        value: todo-namespace-prod-prefix-strip@kubernetescrd
    target:
      kind: Ingress
      name: todo-ingress
      version: v1
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: todo-frontend-storage-prod
    target:
      kind: PersistentVolume
      name: todo-frontend-pv
      version: v1
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: todo-frontend-storage-prod
    target:
      kind: PersistentVolumeClaim
      name: todo-frontend-pvc
      version: v1
