apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-namespace-prod

images:
- name: PROJECT/BC_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-backup-prod-3ddcafe36496c50a87b30a3a9ed92e68af5a6644
- name: PROJECT/BD_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-broadcaster-prod-3ddcafe36496c50a87b30a3a9ed92e68af5a6644
- name: PROJECT/B_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-backend-prod-3ddcafe36496c50a87b30a3a9ed92e68af5a6644
- name: PROJECT/F_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-frontend-prod-3ddcafe36496c50a87b30a3a9ed92e68af5a6644
- name: PROJECT/G_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-generator-prod-3ddcafe36496c50a87b30a3a9ed92e68af5a6644

resources:
- ./../../base
- ./manifests/stuff.yaml

patches:
- path: ./manifests/todo-frontend-patch.yaml
- path: ./manifests/todo-postgres-patch.yaml

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
      value: todo-namespace-prod-prefix-strip@kubernetescrd
  target:
    kind: Ingress
    name: todo-ingress
    version: v1
