apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-namespace
  name: todo-frontend-pvc
spec:
  storageClassName: todo-frontend-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
