apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/L_IMAGE
    newName: deecaad/devopsk8s:part4-1-log-output-3
  - name: PROJECT/P_IMAGE
    newName: deecaad/devopsk8s:part4-1-ping-pong-3
resources:
  - manifests/configmap.yaml
  - manifests/ingress.yaml
  - manifests/log-output.yaml
  - manifests/ping-pong.yaml
  - manifests/postgres.yaml
  - namespaces/namespace.yaml
  - secrets/secret.yaml
