apiVersion: v1
kind: ConfigMap
metadata:
  namespace: todo-namespace
  name: build-configmap
data:
  PRODUCTION: 'true'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: todo-namespace
  name: todo-frontend-pv-prod
spec:
  storageClassName: todo-frontend-storage-prod
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity: ## This is only required for local, it defines which nodes can access it
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-namespace
  name: todo-frontend-pvc-prod
spec:
  storageClassName: todo-frontend-storage-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: todo-namespace
  name: todo-postgres-pv-prod
spec:
  storageClassName: todo-postgres-storage-prod
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity: ## This is only required for local, it defines which nodes can access it
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-namespace
  name: todo-postgres-pvc-prod
spec:
  storageClassName: todo-postgres-storage-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
