apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: todo-namespace
  name: todo-frontend
spec:
  template:
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: todo-frontend-pvc-prod
