apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: myapp-namespace
  name: ping-pong-svc
spec:
  template:
    spec:
      containers:
        - name: ping-pong
          image: PROJECT/P_IMAGE
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: information-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: information-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: information-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: information-configmap
                  key: POSTGRES_PORT
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8081
