apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/G_IMAGE
    newName: deecaad/devopsk8s:partx-y-todo-generator-z
  - name: PROJECT/B_IMAGE
    newName: deecaad/devopsk8s:partx-y-todo-backend-z
  - name: PROJECT/F_IMAGE
    newName: deecaad/devopsk8s:partx-y-todo-frontend-z
resources:
  - crons/todo-generator.yaml
  - manifests/ingress.yaml
  - manifests/todo-backend.yaml
  - manifests/todo-frontend.yaml
  - manifests/todo-postgres.yaml
  - namespaces/namespace.yaml
  - secrets/secret.yaml
