apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo-namespace
  name: todo-generator
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: PROJECT/G_IMAGE
          restartPolicy: Never
