apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-namespace-staging

images:
- name: PROJECT/BC_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-backup-staging-7087fcc721106abefaac8c0e3057ef40eb026cad
- name: PROJECT/BD_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-broadcaster-staging-7087fcc721106abefaac8c0e3057ef40eb026cad
- name: PROJECT/B_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-backend-staging-7087fcc721106abefaac8c0e3057ef40eb026cad
- name: PROJECT/F_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-frontend-staging-7087fcc721106abefaac8c0e3057ef40eb026cad
- name: PROJECT/G_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-generator-staging-7087fcc721106abefaac8c0e3057ef40eb026cad

resources:
- ./../../base
- ./manifests/configmap.yaml

patchesJson6902:
- patch: |-
    - op: add
      path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
      value: todo-namespace-staging-prefix-strip@kubernetescrd
  target:
    kind: Ingress
    name: todo-ingress
    version: v1
