apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-namespace-staging

images:
- name: PROJECT/BC_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-backup-staging-8b187ec0e174738a44da7de0356afe3cffb8cc1b
- name: PROJECT/BD_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-broadcaster-staging-8b187ec0e174738a44da7de0356afe3cffb8cc1b
- name: PROJECT/B_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-backend-staging-8b187ec0e174738a44da7de0356afe3cffb8cc1b
- name: PROJECT/F_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-frontend-staging-8b187ec0e174738a44da7de0356afe3cffb8cc1b
- name: PROJECT/G_IMAGE
  newName: deecaad/devopsk8s
  newTag: todo-generator-staging-8b187ec0e174738a44da7de0356afe3cffb8cc1b

resources:
- ./../../base
- ./manifests/stuff.yaml

patches:
- path: ./manifests/todo-frontend-patch.yaml
- path: ./manifests/todo-postgres-patch.yaml

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
      value: todo-namespace-staging-prefix-strip@kubernetescrd
  target:
    kind: Ingress
    name: todo-ingress
    version: v1
