apiVersion: v1
kind: Secret
metadata:
    namespace: todo-namespace
    name: postgres-secret
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IrHc93VhY8w7JqXG,iv:cehkDXAVLvxxv0T9ZLpP5PQx0MugCSVevq/DIMlBY4g=,tag:3BIITvhuoN0/Wza9FNCeXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xmqm7dgsfv3k0ftyr8g5wza2ztk334pylv5jl9rg0aqkkt6y7sssp342f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOKzd2TjhkN2QvM3VHbTdZ
            bnVQRkxnaVR1anduaDJiQ3loajNlNzZYTGdvClhRckUwOE9ocG5jM1R3NlVHbG9J
            OE1xNVRWNkprOENYeE1STVFKVlJnU28KLS0tIDlOZUNRV1p2OFM4T3FwSGRvdWhi
            TEdVUGZwN1VnT2t0anFxTE40VWlvN0EKaWTgxHhps6EOm65Kgjuva0/05qoA6389
            a9StTgiJ9g+qT5Q/QwLYLg2ayil1iX4BDyDf/jLKeYyaLou0RRViAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T10:24:45Z"
    mac: ENC[AES256_GCM,data:4TjmJcRrL6bKgqtOm1D7l8z4VdN4y7XiafgX5MsNkD0Mrw0P8qxmVc8qpGMYGPt6gX2Qk3PUa50jtpcKGu9VJkyQ24n+WKTZtebKNbEwQMIwoW0jQxXlMcm01HRgWDBjv2vP7LYG3oXJ771slzNGh0MRNMxep58ikr2vHRgYC8s=,iv:rxsQgDKTpUwQmJ6vo+K3wcGYjVaj71tQDP3ufiyYFWA=,tag:XDZVX0oO7WoSs5tN1Nmf2g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
