apiVersion: v1
kind: Service
metadata:
  namespace: todo-namespace
  name: todo-frontend-svc
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-namespace
  name: todo-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      volumes:
        - name: todo-frontend-vol
          persistentVolumeClaim:
            claimName: todo-frontend-pvc
      containers:
        - name: todo-frontend
          image: PROJECT/F_IMAGE
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
          volumeMounts:
            - name: todo-frontend-vol
              mountPath: /usr/src/app/dist/images
              subPath: images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-namespace
  name: todo-frontend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-rwo
