apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - analysis/cpu-analysis.yaml
  - crons/todo-backup.yaml
  - crons/todo-generator.yaml
  - manifests/ingress.yaml
  - manifests/todo-backend.yaml
  - manifests/todo-broadcaster.yaml
  - manifests/todo-frontend.yaml
  - manifests/todo-postgres.yaml
  - namespaces/namespace.yaml
  #- secrets/secret.yaml
  #- secrets/discord-secret.yaml
  #- secrets/google-secret.yaml
