apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/L_IMAGE
  newName: deecaad/devopsk8s
  newTag: log-output-main-fc4f7cf230fddec4938c205e437b2b5d20c616be
- name: PROJECT/P_IMAGE
  newName: deecaad/devopsk8s
  newTag: ping-pong-main-fc4f7cf230fddec4938c205e437b2b5d20c616be
resources:
- manifests/configmap.yaml
- manifests/ingress.yaml
- manifests/log-output.yaml
- manifests/ping-pong.yaml
- manifests/postgres.yaml
- namespaces/namespace.yaml
