apiVersion: v1
kind: Service
metadata:
  namespace: todo-namespace
  name: todo-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8085
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: todo-namespace
  name: todo-frontend
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-analysis
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: todo-frontend-pvc
      containers:
        - name: todo-frontend
          image: PROJECT/F_IMAGE
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/dist/images
