apiVersion: v1
kind: ConfigMap
metadata:
  namespace: todo-namespace
  name: postgres-configmap
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_HOST: todo-postgres-svc
  POSTGRES_PORT: '5432'
---
apiVersion: v1
kind: Service
metadata:
  namespace: todo-namespace
  name: todo-postgres-svc
spec:
  clusterIP: None
  selector:
    app: todo-postgres
  ports:
    - port: 5432
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: todo-namespace
  name: todo-postgres
spec:
  serviceName: todo-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      volumes:
        - name: todo-postgres-vol
          persistentVolumeClaim:
            claimName: todo-postgres-pvc
      containers:
        - name: todo-postgres
          image: postgres:17.0-alpine3.20
          ports:
            - name: web
              containerPort: 5342
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: todo-postgres-vol
              mountPath: /var/lib/postgresql/data
              subPath: postgres
