apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/perttukangas/devops-k8s
    path: part4/8/k8s/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-namespace-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/perttukangas/devops-k8s
    path: part4/8/k8s/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-namespace-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
