apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-time-ping
          persistentVolumeClaim:
            claimName: multi-application-pvc
      containers:
        - name: ping-pong
          image: deecaad/devopsk8s:part1-11-ping-pong
          volumeMounts:
            - name: shared-time-ping
              mountPath: /usr/src/app/files
