apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/G_IMAGE
    newName: deecaad/devopsk8s:part4-2-todo-generator-3
  - name: PROJECT/B_IMAGE
    newName: deecaad/devopsk8s:part4-2-todo-backend-3
  - name: PROJECT/F_IMAGE
    newName: deecaad/devopsk8s:part4-2-todo-frontend-3
  - name: PROJECT/BC_IMAGE
    newName: deecaad/devopsk8s:part4-2-todo-backup-3
resources:
  - crons/todo-backup.yaml
  - crons/todo-generator.yaml
  - manifests/ingress.yaml
  - manifests/todo-backend.yaml
  - manifests/todo-frontend.yaml
  - manifests/todo-postgres.yaml
  - namespaces/namespace.yaml
  - secrets/secret.yaml
  #- secrets/google-secret.yaml
