apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp-namespace
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: deecaad/devopsk8s:part2-6-log-output-1
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: information-configmap
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: information-configmap
            items:
              - key: information.txt
                path: information.txt
