apiVersion: v1
kind: Service
metadata:
  namespace: myapp-namespace
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 2348
      protocol: TCP
      targetPort: 3001
