apiVersion: v1
kind: Secret
metadata:
    namespace: myapp-namespace
    name: postgres-password
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QI5ZHEi5e1KquJn5,iv:sInO61PkRh0f3nvSoERzm0DQW6RQRYuxM6MQ7MClHW8=,tag:/Y1oSyXdV2JCgSVgqBv5/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xmqm7dgsfv3k0ftyr8g5wza2ztk334pylv5jl9rg0aqkkt6y7sssp342f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdDg0ZUZjZXNWNzlYRzk3
            T0ZML0FJR2RudUpVcmoxcGdVVnFkc1VSOUZBCjZxSWtzVGZxYkM1cTFHQVNLVk5K
            UERUNXVCUVBhVURjaHdRemtFcnN4Q1UKLS0tIGhVZFl1ekZ0a3lrZnhoZzRESGpO
            MzVRT0wzN0NDOTlKU0VSMG1qTVdJbVkKtbYRW7yRawDMUi0AYmxi3f2mFAcD/TrI
            wAHOidYGsv/Sm/h3l81CtpzPPMshRaVTkBM6RcLfnh1Gzwe1/woQtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T09:18:32Z"
    mac: ENC[AES256_GCM,data:KicGH5XSOWrc+T5kfWv/P8fy9qU3PimEe1BvH4ARQ2d4Rb4xhCgjzuEdmgku8h58D3LnXCIKATk3Qja6Z5WaxIJhUKLvOMtYN7KbsH1eBjk/4yu+obc5Rsj1e6xnCB2VqoMdBwW34FK5Toe/HzIRAQ3CNSZn3HPVB/KnFkD/D+A=,iv:AFbmK2bIyIimoP9G9WfMdDeL5Mg4Mjgb8hUyY6Jv/ls=,tag:f4ehA/kO3dfgDN53IsG1pw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
