name: Build and publish application

on:
  push:

env:
  BUILD: ${{ startsWith(github.ref, 'refs/tags/') && 'prod' || 'staging' }}

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./part4/8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |-
          docker build --tag "deecaad/devopsk8s:todo-backend-$BUILD-$GITHUB_SHA" ./applications/todo-backend
          docker build --tag "deecaad/devopsk8s:todo-backup-$BUILD-$GITHUB_SHA" ./applications/todo-backup
          docker build --tag "deecaad/devopsk8s:todo-broadcaster-$BUILD-$GITHUB_SHA" ./applications/todo-broadcaster
          docker build --tag "deecaad/devopsk8s:todo-frontend-$BUILD-$GITHUB_SHA" ./applications/todo-frontend
          docker build --tag "deecaad/devopsk8s:todo-generator-$BUILD-$GITHUB_SHA" ./applications/todo-generator

      - name: Publish
        run: |-
          docker push "deecaad/devopsk8s:todo-backend-$BUILD-$GITHUB_SHA"
          docker push "deecaad/devopsk8s:todo-backup-$BUILD-$GITHUB_SHA"
          docker push "deecaad/devopsk8s:todo-broadcaster-$BUILD-$GITHUB_SHA"
          docker push "deecaad/devopsk8s:todo-frontend-$BUILD-$GITHUB_SHA"
          docker push "deecaad/devopsk8s:todo-generator-$BUILD-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          cd k8s

          kustomize edit set image PROJECT/G_IMAGE=deecaad/devopsk8s:todo-generator-$BUILD-$GITHUB_SHA
          kustomize edit set image PROJECT/B_IMAGE=deecaad/devopsk8s:todo-backend-$BUILD-$GITHUB_SHA
          kustomize edit set image PROJECT/F_IMAGE=deecaad/devopsk8s:todo-frontend-$BUILD-$GITHUB_SHA
          kustomize edit set image PROJECT/BC_IMAGE=deecaad/devopsk8s:todo-backup-$BUILD-$GITHUB_SHA
          kustomize edit set image PROJECT/BD_IMAGE=deecaad/devopsk8s:todo-broadcaster-$BUILD-$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: './part4/8/k8s/overlays/$BUILD/kustomization.yaml'
          message: New version released $BUILD ${{ github.sha }}
