name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./part3/3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/todo-generator:$BRANCH-$GITHUB_SHA" ./applications/todo-generator
          docker build --tag "gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA" ./applications/todo-backend
          docker build --tag "gcr.io/$PROJECT_ID/todo-frontend:$BRANCH-$GITHUB_SHA" ./applications/todo-frontend

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/todo-generator:$BRANCH-$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/todo-frontend:$BRANCH-$GITHUB_SHA"

      - name: Echo TODO_PG_SECRET to secrets/secret.yaml
        run: echo "${{ secrets.TODO_PG_SECRET }}" > ./k8s/secrets/secret.yaml

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |-
          cd k8s
          kustomize edit set image PROJECT/G_IMAGE=gcr.io/$PROJECT_ID/todo-generator:$BRANCH-$GITHUB_SHA
          kustomize edit set image PROJECT/B_IMAGE=gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA
          kustomize edit set image PROJECT/F_IMAGE=gcr.io/$PROJECT_ID/todo-frontend:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment -n todo-namespace
          kubectl get services -o wide
